version: "3.8"
services:
  upworkreview-app:
    container_name: upworkreview-app
    restart: always
    build:
      context: .
    networks:
      - db_network
      - web_network
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: upwork
      MYSQL_USER: root
      MYSQL_PASSWORD: NewAccount30
    depends_on:
      - mysql
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - upworkreview-app
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: upwork
      # MYSQL_USER: root
      # MYSQL_PASSWORD: NewAccount30
      MYSQL_ROOT_PASSWORD: NewAccount30
    ports:
      - "3306:3306"
    networks:
      - db_network
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.0.12
    container_name: redis
    command: [ "redis-server", "--port", "6379", "--slave-read-only", "no" ]
    restart: always
    ports:
      - 6379:6379
    networks:
      - db_network
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    networks:
      - db_network
    environment:
      DJANGO_SETTINGS_MODULE: "config.settings"
    command: "celery -A config worker -l info -B"
    depends_on:
      - upworkreview-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  mysql_data: